// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLuWu7oRtGHRl4wfajYjuDZkTowyhaotU',
    appId: '1:990394412416:web:e23bf6a1fbee47f8f66565',
    messagingSenderId: '990394412416',
    projectId: 'epics-bd043',
    authDomain: 'epics-bd043.firebaseapp.com',
    storageBucket: 'epics-bd043.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0oqAImbxOTQJAwNrIyC6CAv7VeAB02iA',
    appId: '1:990394412416:android:c3769987c6f7a058f66565',
    messagingSenderId: '990394412416',
    projectId: 'epics-bd043',
    storageBucket: 'epics-bd043.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeiGdEPysAfu_N2cNEdLcwlFcfxEM9I-E',
    appId: '1:990394412416:ios:3c6067f49cbf057cf66565',
    messagingSenderId: '990394412416',
    projectId: 'epics-bd043',
    storageBucket: 'epics-bd043.appspot.com',
    iosBundleId: 'com.example.epic',
  );
}
